- hosts: ora12node1.foad.local
  tasks:


  - name: Scan ASM Disks
    shell: oracleasm scandisks
  - name: List ASM disks
    shell: oracleasm listdisks

  - parted:
     device: /dev/sda
     number: 1
     state: present
  - name: Create asm OCR_VOTING1 disk
    shell: oracleasm createdisk OCR_VOTING1 /dev/sda1

  - parted:
     device: /dev/sdb
     number: 1
     state: present
  - name: Create asm FRA1 disk
    shell: oracleasm createdisk FRA1 /dev/sdb1
  - parted:
     device: /dev/sdc
     number: 1
     state: present
  - name: Create asm DATA1 disk
    shell: oracleasm createdisk DATA1 /dev/sdc1

