---
# tasks file for oracle11gr2---
- hosts: all

  tasks:

#base:https://www.fatihacar.com/blog/oracle-12c-r3-real-application-clusters-rac-installation-steps-on-oracle-linux-7-7/
  - name: COPY FOAD MOTD
    copy: src=etc/motd.j2 dest=/etc/motd

  - name: upadate etc hosts file
    copy: src=etc/foadhosts.j2 dest=/etc/hosts

  - name: add sattelte server
    get_url:
     url: http://spacewalk.prod.foad.local/pub/katello-ca-consumer-latest.noarch.rpm
     dest: /tmp
  - name: yum install kattelo
    yum:
     name: http://spacewalk.prod.foad.local/pub/katello-ca-consumer-latest.noarch.rpm
     state: present
  - name: Add host to sattelite server
    shell: subscription-manager register --org="FOAD" --activationkey="RHEL7" --force

  - name: Enable repo
    shell: subscription-manager repos --disable='*' --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms  --enable=rhel-7-fast-datapath-rpms  --enable=rhel-7-server-rh-common-rpms --enable=rhel-7-server-optional-rpms
  - name: ensure a list of packages installed
    yum:
     name: "{{ packages }}"
    vars:
     packages:
       - vim
       - mc
       - telnet
       - bash-completion
       - net-tools
       - nm-connection-editor
       - ovirt-guest-agent-common
       - wget
       - bind-utils
       - yum-utils
       - sos
       - psacct
       - binutils
       - libX11
       - compat-libcap1
       - libXau
       - compat-libstdc++-33
       - libaio
       - gcc
       - libaio-devel
       - gcc-c++
       - libdmx
       - glibc-devel
       - glibc
       - ksh
       - make
       - libgcc
       - sysstat
       - libstdc++
       - xorg-x11-utils
       - libstdc++-devel
       - xorg-x11-xauth
       - libXext
       - libXv
       - libXtst
       - libXi
       - libxcb
       - libXt
       - libXmu
       - libXxf86misc
       - libXxf86dga
       - libXxf86vm
       - nfs-utils
       - expect
       - smartmontools 
       - mc
       - unzip
       - unixODBC
       - unixODBC-devel
       - ksh
       - elfutils-libelf
       - elfutils-libelf-devel
       - tuned
       - tuned-profiles-oracle

  
  - name: ensure rhevm-guest-agent-common is at the latest version
    yum: name=ovirt-guest-agent-common state=latest

  - name: ensure ovirt-guest-agent is running (and enable it at boot)
    service: name=ovirt-guest-agent  state=started enabled=yes
  - name: restart ovirt-guest-agent
    service: name=ovirt-guest-agent  state=restarted
  
  - name: ensure qemu-guest-agent is running 
    service: name=qemu-guest-agent state=started enabled=yes
  - name: restart ovirt-guest-agent
    service: name=ovirt-guest-agent  state=restarted


  - name: Set authorized key for root copying it from current user
    authorized_key:
     user: root
     state: present
     key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  - name: clean yum cache
    shell: yum clean all
  - name: be sure firewalld is disabled
    systemd: name=firewalld enabled=no
    tags:
     - install
     - firewalld
  - name: be sure firewalld is stopped 
    systemd: name=firewalld state=stopped
    ignore_errors: yes
    tags:
     - install
     - firewalld
  - name: ensure SELINUX IS IN PERMISIVE MODE
    selinux: policy=targeted state=permissive
  - name: Create a directory gridhome
    file:
     path: /services/oracle/grid/12.2/grid_home
     state: directory
  - name: Create grid base
    file:
     path: /services/oracle/grid/gridbase/
     state: directory
  - name: Create ora home
    file: 
     path: /services/oracle/db/12.2/db_home
     state: directory
    
  - name: Add group asmdba
    group:
     name: asmdba
     gid: 54333
     state: present
    
  - name: Add group asmoper
    group: 
     name: asmoper
     gid: 54334
     state: present
     
  - name: Add group asmadmin
    group: 
     name: asmadmin
     gid: 54335
     state: present
  - name: Add group dba
    group:
     name: dba
     gid: 1030
     state: present
  - name: Add group oinstall
    group:
     name: oinstall
     gid: 1012
     state: present
  - name: add hosts file   
    copy: src=etc/oracle12hosts.j2  dest=/etc/hosts
  - name: oracle limits
    copy: src=etc/oracle90-nproc.conf.j2 dest=/etc/security/limits.d/90-nproc.conf
  - name: Add gpg key for oracle repo
    get_url:
     url: http://public-yum.oracle.com/RPM-GPG-KEY-oracle-ol7 
     dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
  - name: kernel parm
    copy: src=etc/oraclelimits.conf.j2  dest=/etc/security/limits.conf
  - name: kernel read
    shell: sysctl -p

  - name:  Make sure a service tumed is running
    systemd:
      state: started
      name: tuned.service
  - name: Activate the tuned-profiles-oracle profile
    shell: tuned-adm profile oracle
  - name: For the grub changes to take effect, run the following 
    shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  - name: Install kmod-oracleasm
    yum:
     name: kmod-oracleasm
     state: present
  - name: Install oracleasm-support
    yum:
     name: ftp://puppetmaster.foad.local/pub/oracle12rac/oracleasm-support-2.1.11-2.el7.x86_64.rpm 
     state: present
  - name: Install cvudisk
    yum: 
     name: ftp://puppetmaster.foad.local/pub/oracle12rac/cvuqdisk-1.0.10-1.rpm
     state: present
  - name: Install oracleasmlib
    yum:
     name: ftp://puppetmaster.foad.local/pub/oracle12rac/oracleasmlib-2.0.12-1.el7.x86_64.rpm
     state: present
  - name: Reboot cluster nodes
    reboot:
     msg: "Reboot initiated by Ansible"
     connect_timeout: 5
     reboot_timeout: 600
     pre_reboot_delay: 0
     post_reboot_delay: 30
     test_command: whoami

  - name: be sure ntp is enabled
    service: name=ntpd state=started enabled=yes
  - name: add ntp configuration file
    copy: src=etc/ntprht.j2  dest=/etc/ntp.conf
  - name: Sync ntp to puppetmaster.foad.local
    shell: service ntpd stop && ntpdate puppetmaster.foad.local && service ntpd start
    tags: ntp
  - name: Make sure Chrony is stopped up
    service: name=chronyd state=stopped enabled=no
    tags: chrony 
  - name: Remove Chrony 
    yum:
      name: chrony
      state: absent
  - name: Umask 022
    copy: src=etc/oracle12racprofile.j2  dest=/etc/profile
  - name: grid and ora install X
    yum:
     name: xorg-x11-server-utils
     state: present

  - name: read kern parm before install
    shell: sysctl -p
  - name: Check if user grid exists
    command: getent passwd grid
    ignore_errors: yes

  - name: add grid user
    user: 
     name: grid
     uid: 5431
     group: oinstall
     shell: /bin/bash
     home: /services/oracle/gridhome
     state: present
  - name: add extra group for griduser
    user:
     name: grid
     groups: oinstall,dba
     append: yes

  - name: add oracle user
    user: 
     name: oracle
     uid: 5432
     group: oinstall
     shell: /bin/bash
     home: /services/oracle/orahome
     state: present

  - name: add extra group for oracle
    user:
     name: oracle
     groups: oinstall,dba
     append: yes

     
  - name:  Permission for oracle
    file:
     path: /services/oracle
     state: directory
     recurse: yes
     owner: oracle
     group: oinstall
  - name:  Permission for grid
    file:
     path: /services/oracle/grid
     state: directory
     recurse: yes
     owner: grid
     group: oinstall
  - name: Permision for gridhome
    file:
     path: /services/oracle/gridhome
     state: directory
     owner: grid
     group: oinstall
      
  - name: Oracle folder permision
    file:
     path: /services/oracle
     state: directory
     mode: '0775'

  - name: Create a 2048-bit SSH key for user oracle
    user:
      name: oracle
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa  

  - name: Set oracle user password
    shell: echo Jb0ss42| passwd --stdin oracle

  - name: Create a 2048-bit SSH key for usergrid
    user:
       name: grid
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa


  - name: Set grid user password
    shell: echo Jb0ss42| passwd --stdin grid
  - name: Run ASM driver configureation
    become: yes
    become_user: root
    shell: |
      spawn oracleasm configure -i
       sleep 5
       expect "\[Default user to own the driver interface []:\n" 
       send -- "grid\r"
       expect "\[Default group to own the driver interface []:]\n" 
       send -- "dba\r"
       expect "\[Scan for Oracle ASM disks on boot (y/n):]\n"
       send -- "y\r"
       expect "\[Writing Oracle ASM library driver configuration: done]\n"
       send -- "\r"
       expect eof

    args: 
      executable: /usr/bin/expect   
   
  - name:  initialize the asm disk
    shell: oracleasm init
  - name: Scan ASM Disks
    shell: oracleasm scandisks 
  - name: List ASM disks
    shell: oracleasm listdisks
- hosts: ora12node1.foad.local
  tasks:

  - name: upadate bash profile for grid user node1
    copy: 
     src: bash/oracle12gridbashnode1.j2
     dest: /services/oracle/gridhome/.bash_profile

  - name: upadate bash profile for oracle user
    copy: 
     src: bash/oracle12bashnode1.j2
     dest: /services/oracle/orahome/.bash_profile
  - name: Scan ASM Disks
    shell: oracleasm scandisks
  - name: List ASM disks
    shell: oracleasm listdisks

  - parted:
     device: /dev/sda
     number: 1
     state: present
  - name: Create asm OCR_VOTING1 disk
    shell: oracleasm createdisk OCR_VOTING1 /dev/sda1

  - parted:
     device: /dev/sdb
     number: 1
     state: present
  - name: Create asm FRA1 disk
    shell: oracleasm createdisk FRA1 /dev/sdb1
  - parted:
     device: /dev/sdc
     number: 1
     state: present
  - name: Create asm DATA1 disk
    shell: oracleasm createdisk DATA1 /dev/sdc1

  - name: Set ASM disks permisions
    shell: chown -R grid:dba /dev/oracleasm/disks/*
  - name: Copy grid archive linuxx64_12201_grid_home.zip
    get_url:
      url: ftp://puppetmaster.foad.local/pub/oracle12rac/linuxx64_12201_grid_home.zip 
      dest: /tmp
      owner: grid
      group: dba
  - name: Extract Grid archive LINUX.X64_123000_grid_home.zip
    unarchive:
     src: /tmp/linuxx64_12201_grid_home.zip
     dest: /services/oracle/grid/12.2/grid_home
     remote_src: yes
     owner: grid
     group: dba

  - name: Copy oracle archive linuxx64_12201_database.zip
    get_url:
      url: ftp://puppetmaster.foad.local/pub/oracle12rac/linuxx64_12201_database.zip
      dest: /tmp
      owner: oracle
      group: dba

  - name: Extract Oracle archive linuxx64_12201_database.zip
    unarchive:
     src: /tmp/linuxx64_12201_database.zip
     dest: /services/oracle/db/12.2/db_home
     remote_src: yes
     owner: oracle
     group: dba


- hosts: ora12node2.foad.local
  tasks:

  - name: upadate bash profile for grid user node2
    copy:
     src: bash/oracle12gridbashnode2.j2 
     dest: /services/oracle/gridhome/.bash_profile

  - name: upadate bash profile for oracle user
    copy:
     src: bash/oracle12bashnode2.j2
     dest: /services/oracle/orahome/.bash_profile
  - name: Scan ASM Disks
    shell: oracleasm scandisks
  - name: List ASM disks
    shell: oracleasm listdisks
  - name: Set ASM disks permisions
    shell: chown -R grid:dba  /dev/oracleasm/disks/*
